import type { Product } from './product.types';

// За MVP продуктите могат да стоят директно в кода.
// По-късно този масив лесно може да се замени с данни от Supabase, CMS или админка.
export const products: Product[] = [
  {
    id: 'cake-1',
    name: 'Горски минимализъм',
    category: 'cakes',
    priceMinor: 2301,
    description: 'Нежен ванилов блат със свежи плодове и лек крем чийз. Идеален за празник.',
    image: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=800&q=80',
    weight: '1.5 кг (6-8 порции)',
    filling: 'Ягода-малина, крем чийз',
    prepTime: '2-3 дни',
  },
  {
    id: 'cake-2',
    name: 'Шоколадов трюфел',
    category: 'cakes',
    priceMinor: 2659,
    description: 'Наситена шоколадова торта със сочен блат и ганаш от черен шоколад.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80',
    weight: '2 кг (10-12 порции)',
    filling: 'Шоколадов ганаш, хрупкав слой с пралине',
    prepTime: '2-3 дни',
  },
  {
    id: 'cake-3',
    name: 'Класически медовик',
    category: 'cakes',
    priceMinor: 2045,
    description: 'Традиционна медена торта със сметанов крем. Топи се в устата.',
    image: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=800&q=80',
    weight: '1.8 кг (8-10 порции)',
    filling: 'Медени блатове, сметанов крем',
    prepTime: '2 дни',
  },
  {
    id: 'cin-1',
    name: 'Класически синнабон',
    category: 'cinnabons',
    priceMinor: 179,
    description: 'Топла пухкава канелена ролка с фирмена сметанова глазура.',
    image: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=800&q=80',
    weight: '250 г',
    filling: 'Канела, кафява захар',
    prepTime: 'В наличност или 1 ден',
  },
  {
    id: 'cin-2',
    name: 'Шокобон с пекан',
    category: 'cinnabons',
    priceMinor: 215,
    description: 'Ролка с шоколадов пълнеж, карамел и ядки пекан.',
    image: 'https://images.unsplash.com/photo-1616801646274-124b11f0cbab?w=800&q=80',
    weight: '280 г',
    filling: 'Шоколад, карамел, пекан',
    prepTime: 'В наличност или 1 ден',
  },
  {
    id: 'cin-3',
    name: 'Плодов синнабон',
    category: 'cinnabons',
    priceMinor: 194,
    description: 'Пухкава ролка с домашно малиново сладко и крем чийз.',
    image: 'https://images.unsplash.com/photo-1616801646274-124b11f0cbab?w=800&q=80',
    weight: '260 г',
    filling: 'Малина, крема сирене',
    prepTime: 'В наличност или 1 ден',
  },
  {
    id: 'combo-1',
    name: 'Сет "Уютна вечер"',
    category: 'combos',
    priceMinor: 920,
    description: 'Кутия с 6 пресни синнабона: 3 класически и 3 шоколадови. Добър избор за компания.',
    image: 'https://images.unsplash.com/photo-1603532648955-039310d9ed75?w=800&q=80',
    weight: '1.5 кг',
    prepTime: '1 ден',
  },
  {
    id: 'combo-2',
    name: 'Празничен сет',
    category: 'combos',
    priceMinor: 1636,
    description: 'Асорти от 9 мини синнабона с различни вкусове. Подходящо за голяма маса.',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80',
    weight: '1.8 кг',
    prepTime: '1 ден',
  },
  {
    id: 'combo-3',
    name: 'Сет за двама',
    category: 'combos',
    priceMinor: 460,
    description: '2 синнабона по избор и 2 порции филтър кафе или авторски чай.',
    image: 'https://images.unsplash.com/photo-1495474472205-51e7d9b932dc?w=800&q=80',
    weight: '800 г',
    prepTime: 'В наличност',
  }
];
